name: Deploy Site

on:
  push:
    branches: ["main"]
    paths-ignore:
      - .github/workflows/**
      - README.md
      - .gitignore

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS Environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      
      - name: Install Packages
        run: npm ci
      
      - name: Build Site
        run: npm run build -if-present

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          branch: gh-pages
          folder: public
